Initial scaffolding for testing
prairir/microblog pull request #27
Opened 2023-03-08 03:09 UTC by Aleksa-Vig

**Description**

-Added folder structure for tests and well as readme's for use
-Added testing examples for inspiration

2023-03-08 05:54 UTC, jere-mie requested changes
Good work overall, see requested changes though

2023-03-08 05:54 UTC, jere-mie commented on tests/features/steps/add-task-steps.py
> +from behave import *
bad practice to `import *`, change to import only what you need

2023-03-08 05:54 UTC, jere-mie commented on tests/features/steps/check-ui-steps.py
> +from behave import *
same here

2023-03-08 20:37 UTC, prairir commented
funniest part is jeremie is right, that is bad practice

2023-03-08 21:31 UTC, prairir requested changes
Overall great work, I have a few comments. mostly nitpicks but the headless browser stuff I think will be a real issue as theres no display server on the ec2.

2023-03-08 21:31 UTC, prairir commented on tests/features/steps/add-task-steps.py
> +    context.driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
We should make this a headless as it might cause runtime errors on jenkins.

2023-03-08 21:31 UTC, prairir commented on tests/features/steps/add-task-steps.py
> +@when(u'I click the "Add" button')
nit pick
```suggestion
@when("I click the 'Add' button")
```

since all strings in python3 are unicode strings, no need to have an explicit one.

2023-03-08 21:31 UTC, prairir commented on tests/features/steps/check-ui-steps.py
> +    context.driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
again as above with headless browsing

2023-03-08 21:31 UTC, prairir commented on tests/features/steps/check-ui-steps.py
> +@then(u'the page should have a text field to enter the title of the task')
also same as above for unicode strings, this goes for all `u'..'` strings. its just a nitpick tho

2023-03-08 21:31 UTC, prairir commented on tests/unit/how-to-run-tests.md
> +How to run unit tests
I would prefer we put testing instructions in the `README.md` as it should be the central point for all big info in our project

2023-03-08 21:31 UTC, prairir commented on tests/unit/how-to-run-tests.md
> +
you put `\` in this for file paths and `/` in the next step. Please keep it consistent. I am partial to `/` as its the unix one(manraj, zain, brady, and I use unix based systems).

2023-03-09 00:51 UTC, Aleksa-Vig commented
@prairir  @jere-mie Addressed the issues. The headless chrome implementation may be unstable on linux we will need to check it out later.

2023-03-09 02:42 UTC, prairir commented
I am very ok with not using chrome and instead using firefox if need be. I am more worried about chrome throwing an error on startup because there is no display server

2023-03-09 20:54 UTC, jere-mie approved these changes
LGTM 🚀🚀🚀

2023-03-10 16:54 UTC, prairir approved these changes

2023-03-10 16:54 UTC, merged